export const CREATE_POST = "POST/CREATE_POST"
export const DELETE_POST = "POST/DELETE_POST"
export const AXIOS_POST = "POST/AXIOS_POST"
export const SHOW_LOADER = "POST/DELETE_POST"
export const HIDE_LOADER = "POST/DELETE_POST"

